---
# 12. PV - BUSINESS RULES PROPERTIES
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scc-business-rule-service-props
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.192.150.26
    path: /properties/scc/business-rule-service
  persistentVolumeReclaimPolicy: Retain

---
# 13. PVC - BUSINESS RULES PROPERTIES
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scc-business-rule-service-props
  namespace: comisiones
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-scc-business-rule-service-props

---
# 14. SERVICE - BUSINESS RULE (INTERNO)
apiVersion: v1
kind: Service
metadata:
  name: business-rule-service
  namespace: comisiones
  labels:
    app: business-rule-service
    uso: gestion_parametros
spec:
  selector:
    app: business-rule-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# 15. DEPLOYMENT - BUSINESS RULE SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-rule-service
  namespace: comisiones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-rule-service
  template:
    metadata:
      labels:
        app: business-rule-service
        encargado: dominio_crm
        api: SCC.BusinessRules.Management
    spec:
      containers:
        - name: business-rule-service
          image: cfregistryvp01.corp.digitel.com.ve:444/business-rule-service:1.0.0
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1.0"
              memory: "512Mi"
          env:
            # --- POSTGRES VARIABLES ---
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: scc-db-secrets
                  key: pg_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scc-db-secrets
                  key: pg_pass
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: POSTGRES_DB
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: POSTGRES_PORT
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: DB_SCHEMA

            # --- PARÁMETROS GLOBALES ---
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: TZ
          volumeMounts:
            - name: props
              mountPath: /app/config
      volumes:
        - name: props
          persistentVolumeClaim:
            claimName: pvc-scc-business-rule-service-props