---
# 20. PV - CLAIMS PROPERTIES
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scc-claims-service-props
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.192.150.26
    path: /logs/scc/claims-service # Nota: Ajustado a path de logs/props según estándar
  persistentVolumeReclaimPolicy: Retain

---
# 21. PVC - CLAIMS PROPERTIES
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scc-claims-service-props
  namespace: comisiones
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-scc-claims-service-props

---
# 22. SERVICE - CLAIMS (INTERNO)
apiVersion: v1
kind: Service
metadata:
  name: claims-service
  namespace: comisiones
  labels:
    app: claims-service
    uso: gestion_reclamos_agentes
spec:
  selector:
    app: claims-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# 23. DEPLOYMENT - CLAIMS SERVICE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-service
  namespace: comisiones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims-service
  template:
    metadata:
      labels:
        app: claims-service
        encargado: dominio_crm
        api: SCC.Claims.Management
    spec:
      containers:
        - name: claims-service
          image: cfregistryvp01.corp.digitel.com.ve:444/claims-service:1.0.0
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1.0"
              memory: "512Mi"
          env:
            # --- POSTGRES VARIABLES ---
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: scc-db-secrets
                  key: pg_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scc-db-secrets
                  key: pg_pass
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: POSTGRES_DB
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: POSTGRES_PORT
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: DB_SCHEMA

            # --- PARÁMETROS GLOBALES ---
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: scc-config-global
                  key: TZ
          volumeMounts:
            - name: props
              mountPath: /app/config
      volumes:
        - name: props
          persistentVolumeClaim:
            claimName: pvc-scc-claims-service-props